backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
log-level = "warn";
shadow-ignore-shaped = false;

# Opacity
inactive-opacity = 0.8;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

blur-background = true;
blur-method = "kawase";
blur-strength = 6;
